export const REQUEST_FETCH_USER = "REQUEST_FETCH_USER";
export const RECEIVE_FETCH_USER_SUCCESS = "RECEIVE_FETCH_USER_SUCCESS";
export const REQUEST_FETCH_USER_FAILURE = "REQUEST_FETCH_USER_FAILURE";

export const USER_ACTION_TYPES = [
  REQUEST_FETCH_USER,
  RECEIVE_FETCH_USER_SUCCESS,
  REQUEST_FETCH_USER_FAILURE
];
